import type { Metadata } from "next";
import Sidebar from "@/components/layout/app-layout/Sidebar";
import MainContainerApp from "@/components/layout/app-layout/MainContainerApp";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MainContainerApp>
      <Sidebar />
      {children}
    </MainContainerApp>
  );
}
