import type { Metadata } from "next";
import MainContainer from "@/components/layout/MainContainer";
import Header from "@/components/layout/Header";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MainContainer>
      <Header />
      {children}
    </MainContainer>
  );
}
